export const products = [
  {
    id: 'botanical-affirmation-wall-art',
    name: 'Botanical Affirmation Wall Art',
    description: 'Minimalist botanical line art with refined affirmation quote "You Are Enough". Perfect for any room.',
    price: 4.50,
    category: 'Wall Art',
    colors: ['Sage Green', 'Warm Cream', 'Terracotta'],
    image: '/src/assets/products/wall-art-botanical-affirmation-001.png',
    lemonSqueezyUrl: import.meta.env.VITE_LS_WALL_ART_URL || '#',
  },
  {
    id: 'clean-minimal-weekly-planner',
    name: 'Clean Minimal Weekly Planner',
    description: 'Undated weekly spread with vertical time slots and priority sections. US Letter size.',
    price: 5.00,
    category: 'Planners',
    colors: ['Soft Blush', 'Warm Gray', 'Cream'],
    image: '/src/assets/products/weekly-planner-clean-minimal-001.png',
    lemonSqueezyUrl: import.meta.env.VITE_LS_PLANNER_URL || '#',
  },
  {
    id: 'monthly-budget-tracker',
    name: 'Monthly Budget Tracker',
    description: 'Modern finance organizer with income/expense tracking and savings goal visuals.',
    price: 5.00,
    category: 'Finance',
    colors: ['Navy', 'Gold', 'Teal'],
    image: '/src/assets/products/budget-tracker-modern-001.png',
    lemonSqueezyUrl: import.meta.env.VITE_LS_BUDGET_URL || '#',
  },
  {
    id: 'monthly-habit-tracker-grid',
    name: 'Monthly Habit Tracker Grid',
    description: '31-day grid for tracking up to 12 habits with motivational streak sections.',
    price: 4.00,
    category: 'Habits',
    colors: ['Sage Green', 'Blush Pink', 'Warm Gray'],
    image: '/src/assets/products/habit-tracker-monthly-001.png',
    lemonSqueezyUrl: import.meta.env.VITE_LS_HABIT_URL || '#',
  },
  {
    id: 'weekly-meal-planner-grocery-list',
    name: 'Weekly Meal Planner & Grocery List',
    description: 'One-page comprehensive menu plan and categorized grocery list.',
    price: 4.50,
    category: 'Kitchen',
    colors: ['Terracotta', 'Olive Green', 'Warm Brown'],
    image: '/src/assets/products/meal-planner-weekly-001.png',
    lemonSqueezyUrl: import.meta.env.VITE_LS_MEAL_URL || '#',
  },
];
